name: state_notifier
description: ValueNotifier, but outside Flutter and with some extra perks
version: 0.4.0
author: Remi Rousselet <darky12s@gmail.com>
homepage: https://github.com/rrousselGit/state_notifier

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  test: ^1.12.0
  mockito: ^4.1.1
  matcher: ^0.12.6