name: flutter_state_notifier
description: Flutter bindings for state_notifier (providers, builders)
version: 0.4.0
author: Remi Rousselet <darky12s@gmail.com>
homepage: https://github.com/rrousselGit/state_notifier

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  flutter:
    sdk: flutter
  provider: ">= 4.0.0 < 5.0.0"
  state_notifier: ">= 0.3.0 < 1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  matcher: ^0.12.6
